import React, { useEffect, useState } from 'react';
import { fetchLogs } from '../api/logs';
import { useAuth } from '../context/AuthContext.jsx';

const Settings = () => {
  const { user, refresh } = useAuth();
  const [logs, setLogs] = useState([]);

  useEffect(() => {
    const load = async () => setLogs(await fetchLogs());
    load();
  }, []);

  return (
    <div className="space-y-6">
      <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6">
        <h2 className="text-lg font-semibold text-white">Account</h2>
        <p className="text-sm text-slate-400">Authenticated as {user.username}. Use the CLI to rotate passwords.</p>
        <button
          type="button"
          className="mt-4 rounded-md border border-slate-700 px-4 py-2 text-sm text-slate-300 hover:bg-slate-800"
          onClick={refresh}
        >
          Refresh session
        </button>
      </section>

      <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-semibold text-white">Audit logs</h2>
            <p className="text-sm text-slate-400">Actions generated by alliance, minister, attendance, and gift modules.</p>
          </div>
          <button
            type="button"
            className="rounded-md border border-slate-700 px-3 py-2 text-xs text-slate-300 hover:bg-slate-800"
            onClick={async () => setLogs(await fetchLogs())}
          >
            Refresh
          </button>
        </div>
        <div className="mt-6 max-h-96 overflow-y-auto">
          <ul className="space-y-3 text-sm text-slate-300">
            {logs.map((log) => (
              <li key={log.id} className="rounded-lg border border-slate-800 bg-slate-900/80 p-3">
                <div className="flex items-center justify-between text-xs text-slate-500">
                  <span className="uppercase tracking-wide">{log.category}</span>
                  <span>{new Date(log.created_at).toLocaleString()}</span>
                </div>
                <p className="mt-2 text-slate-200">{log.message}</p>
              </li>
            ))}
          </ul>
        </div>
      </section>
    </div>
  );
};

export default Settings;
